#!/usr/bin/perl
#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::Build::CreateLinks  qw(:all);


#
# nethserver-dante-update event
#

# actions to execute
event_actions('nethserver-dante-update', qw(
      initialize-default-databases   00
      nethserver-dante-conf          03
));

# templates to expand
event_templates('nethserver-dante-update', qw(
    /etc/httpd/conf.d/dante.conf
    /usr/share/dante/beatrice/config.js
    /etc/sysconfig/dante
    /etc/cron.d/dante
));

# services to restart
event_services('nethserver-dante-update', qw(
    httpd reload
    virgilio restart
));

