#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $input = readInput();
my $ret = {};
my $db = esmith::ConfigDB->open_ro();

my $hostname = $input->{'hostname'} || '';
$ret->{'url'} = "https://$hostname/".$db->get_prop('dante','alias');

$ret->{'url'} .= "/#?theme=".$db->get_prop('dante','Theme')."&palette=".$db->get_prop('dante','Palette')."&last=".$db->get_prop('dante','Interval')."&lang=".$db->get_prop('dante','Language');

print encode_json($ret);
