#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use Sys::Hostname;
use File::Basename;
use JSON;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};
my $ret = {};

if ($cmd eq 'configuration') {
    my $db = esmith::ConfigDB->open_ro();

    my $dante = $db->get('dante');
    my %props = $dante->props;

    if ($props{'PublicHost'} eq '') {
        $props{'PublicHost'} = hostname();
    }
    delete($props{'type'});

    foreach (keys %props) {
        $ret->{'settings'}{$_} = $props{$_};
    }

    $ret->{'settings'}{'MailDestinations'} = [];
    foreach (split(/,/,$props{'MailDestinations'})) {
        my ($time, $mail) = split(/;/, $_);
        push(@{$ret->{'settings'}{'MailDestinations'}}, {"time" => $time, "mail" => $mail});
    }
} elsif ($cmd eq 'languages') {
    $ret->{'languages'} = [];
    foreach (glob q("/usr/share/dante/beatrice/i18n/??.json")) {
        my($filename, $dirs, $suffix) = fileparse($_, (".json"));
        push(@{$ret->{'languages'}}, $filename);
    }
}
print encode_json($ret);
